# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args:
    - --profile=black
- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
  - id: black
    args: [project, tests]
- repo: https://github.com/PyCQA/pylint
  rev: v2.17.0
  hooks:
  - id: pylint
    args: [--disable=import-error, project, tests] # Environment dependent ignored.
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.2
  hooks:
  - id: codespell
    types_or: [python, markdown]
    additional_dependencies: [tomli]
